services:
  lab:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: lab
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/labdb
      DB_USER: log430
      DB_PASSWORD: log430
      SPRING_PROFILES_ACTIVE: prod

    volumes:
      - /src/main/resources/application-prod.properties:/app/config/application-prod.properties
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: log430
      POSTGRES_PASSWORD: log430
      POSTGRES_DB: labdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata: