global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'Lab API Metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      #- targets: ['lab1:8080', 'lab2:8080']
      - targets: ['lab:8080']