@startuml
skinparam title {
  FontColor #66BB66
}

title UC1 - Generate Store Sales Report
autonumber

actor Manager as m
participant "StoreController" as sc
participant "StoreService" as ss
participant "StoreMapper" as sm
participant "StoreRepository" as sr
database "PostgreSQL" as db

m -> sc: Request to generate report
activate sc
sc -> ss: generateReport()
activate ss
ss -> sr: findAll()
activate sr
sr -> db: SELECT * FROM stores
activate db
db --> sr: List of stores
deactivate db
sr --> ss: List of stores
deactivate sr
ss -> sm: storeToStoresReportDto(stores)
activate sm
sm --> ss: StoreMetricsDto
deactivate sm
ss --> sc: List of StoreMetricsDto
deactivate ss
sc --> m: Return report
deactivate sc

@enduml